version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/nsttt/sonarr/config:/config
      - /mnt/Alpha/Media:/media
      - /mnt/Downloads/complete:/downloads/complete
    ports:
      - 8989:8989
    restart: unless-stopped
